"""
diplomacy_kg_schema.py — design sketch, not a runtime.

The shape of the redesigned knowledge graph for the diplomacy agent.
This file is meant to be read top-to-bottom; the comments are part of the
design. None of this is hooked to the engine yet — the goal here is to make
the structure precise enough to discuss, not to run.

Design constraints carried forward from magic_kg_v4_6:
  - Beliefs are accountable to events (deterministic graders, not LLM self-grading).
  - Retrieval is broad, display is narrow (mental fovea).
  - Lifecycle is outcome-driven (promote / retire / revise based on what happened).
  - Hand-rolled scoring is fine, but every score has a traceable source.
  - The LLM proposes; deterministic code grades.

Diplomacy-specific commitments:
  - Cross-game persistence: dispositions persist; tactical_patterns and
    risk_assessments reset. (See `BeliefType`.)
  - Commitspeak is REQUIRED for all trackable promises. Natural language
    around it is fine, but only commitspeak-tagged commitments enter the
    graph. Easier on small models (template-fill, not free-form
    extraction) and removes a confabulation surface.
  - Predictions are REQUIRED at every orders call. At least one prediction
    must have a near-term window (next phase) so the lifecycle gets fresh
    grading signal every turn. Longer-window predictions are welcome but
    do not substitute for near-term ones.
  - Strategy gets the full magic_go lifecycle: proto_strategy → active →
    retired/revised, with intent commitment carrying plans across multiple
    phases, with revision proposals when an intent's predictions fail.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, Literal
import time
import uuid


# =============================================================================
# LAYER 0 — Observations (deterministic ground truth, never retired)
# =============================================================================
# These are facts captured by the engine after adjudication. They are the
# bedrock against which every higher-level claim is graded. Nothing in this
# layer is generated by the LLM. Nothing in this layer ever gets retired,
# revised, or have its hp adjusted — they are the substrate.

PowerName = str          # "FRANCE", "RUSSIA", etc.
ProvinceCode = str       # "PAR", "MAR", "STP"
Season = Literal["SPRING", "FALL", "WINTER"]
Phase = Literal["MOVES", "RETREATS", "ADJUSTMENTS"]
PhaseKey = str           # canonical "1902-FALL-MOVES"


def new_id(prefix: str) -> str:
    return f"{prefix}:{uuid.uuid4().hex[:8]}"


def phase_key(year: int, season: Season, phase: Phase) -> str:
    return f"{year}-{season}-{phase}"


@dataclass
class MoveEvent:
    """A single ordered move, after adjudication."""
    id: str
    phase: PhaseKey
    power: PowerName
    unit_kind: Literal["A", "F"]
    origin: ProvinceCode
    order_type: Literal["HOLD", "MOVE", "SUPPORT", "CONVOY", "RETREAT", "DISBAND", "BUILD"]
    target: Optional[ProvinceCode]              # destination for MOVE/RETREAT
    support_of: Optional[str]                   # for SUPPORT, the unit being supported
    result: Literal["success", "bounced", "cut", "dislodged", "void"]
    resolved_at: float


@dataclass
class MessageEvent:
    """A press message that was sent. Captured at send time."""
    id: str
    phase: PhaseKey
    sender: PowerName
    recipients: list[PowerName]                 # empty list ⇒ public
    public: bool
    body: str                                   # free-text natural language
    commitspeak_tail: Optional[str]             # raw structured tail if present
    sent_at: float


@dataclass
class PhaseState:
    """Board snapshot at a phase boundary. Indexed by phase_key."""
    id: str
    phase: PhaseKey
    sc_owner: dict[ProvinceCode, PowerName]     # who owns each SC
    units_by_power: dict[PowerName, list[tuple[Literal["A", "F"], ProvinceCode]]]
    eliminated: set[PowerName]
    captured_at: float


@dataclass
class AdjustmentEvent:
    """Build, disband, or elimination at a winter phase."""
    id: str
    phase: PhaseKey
    power: PowerName
    kind: Literal["BUILD", "DISBAND", "ELIMINATED"]
    unit_kind: Optional[Literal["A", "F"]]      # None for ELIMINATED
    location: Optional[ProvinceCode]


# A power's actions across a phase, indexed for fast lookup by graders.
@dataclass
class PowerPhaseFootprint:
    """Pre-aggregated for grading: what did POWER do this PHASE?"""
    phase: PhaseKey
    power: PowerName
    moves: list[MoveEvent]
    builds: list[AdjustmentEvent]
    disbands: list[AdjustmentEvent]
    sc_count_after: int
    units_after: list[tuple[Literal["A", "F"], ProvinceCode]]


# =============================================================================
# LAYER 1 — Commitments (the bridge from messages to events)
# =============================================================================
# Every press message MAY carry a commitspeak tail. Only commitspeak-tagged
# claims become CommitmentNodes. Natural-language promises in the body are
# advisory and never tracked — if the speaker wants their promise to count,
# they must close the message with a [[commit ...]] block.
#
# This is a deliberate constraint:
#   - It removes a major confabulation surface (LLM extracting from prose).
#   - It gives the speaking LLM a clear, fillable template that small models
#     handle reliably.
#   - It puts the speaker on notice: structured promises are tracked.
#   - The recipient's KG can grade them precisely against engine events.

class CommitmentType(Enum):
    """The closed universe of commitment kinds we'll grade.

    Adding a kind here means writing a grader for it.
    Anything outside this universe is rejected at parse time —
    it never becomes a node.
    """
    MOVE_TO            = "move_to"           # "I'll move A WAR to GAL"
    NOT_MOVE_TO        = "not_move_to"       # "I won't enter the Black Sea"
    HOLD_AT            = "hold_at"           # "F BUL holds this turn"
    SUPPORT            = "support"           # "I'll support A KIE → BER"
    NON_AGGRESSION     = "non_aggression"    # "We do not move against each other this turn"
    DEMILITARIZE       = "demilitarize"      # "We both leave Galicia empty"
    ALLIANCE_FOR       = "alliance_for"      # "Allied vs RUSSIA through 1903"
    BUILD              = "build"             # "I will build a fleet at TRI in W1902"
    DISBAND            = "disband"           # rare but possible


class CommitmentStatus(Enum):
    PENDING       = "pending"
    KEPT          = "kept"
    BROKEN        = "broken"
    IRRELEVANT    = "irrelevant"     # situation changed; no longer testable
    UNPARSEABLE   = "unparseable"    # malformed commitspeak; logged for debugging


@dataclass
class CommitmentNode:
    """A structured promise extracted from a commitspeak block.

    DESIGN NOTE: A commitment is testable only if (deadline_phase, type, subject)
    together pin down a question that the engine state can answer yes/no after
    deadline_phase resolves. Parsing rejects anything that doesn't.
    """
    id: str
    source_msg_id: str
    speaker: PowerName
    addressees: list[PowerName]                 # empty ⇒ public commitment

    type: CommitmentType
    subject_unit: Optional[str]                 # "A WAR" if specified
    subject_province: Optional[ProvinceCode]    # the relevant province
    target_province: Optional[ProvinceCode]     # for MOVE_TO/SUPPORT/etc.
    counterparty: Optional[PowerName]           # for ALLIANCE_FOR/NON_AGGRESSION
    deadline_phase: PhaseKey                    # phase by which it must be honored

    conditional_on: Optional[str]               # natural-language condition (logged, not auto-graded)

    status: CommitmentStatus = CommitmentStatus.PENDING
    resolved_at_phase: Optional[PhaseKey] = None
    grading_evidence: list[str] = field(default_factory=list)
                                                # MoveEvent / AdjustmentEvent / PhaseState ids

    raw_commitspeak_line: str = ""              # the exact line as written, for debugging


# Self-commitments: same shape, different origin and grader path.
@dataclass
class SelfCommitmentNode(CommitmentNode):
    """A commitment WE made to others. Tracked because future credibility
    depends on our own kept/broken record."""
    target_power: Optional[PowerName] = None    # who we made the promise to


# -----------------------------------------------------------------------------
# Commitspeak — the constrained structured tail (REQUIRED for tracked promises)
# -----------------------------------------------------------------------------
# A press message MAY append a commitspeak block. Only commitspeak commitments
# enter the graph. The free-text body of the message is whatever the
# personality wants it to be — Cardinal Fox can monologue about destiny;
# Marshal Veil can be terse. The commitspeak tail is independent of voice.
#
# GRAMMAR:
#
#   message_body
#   [[commit
#     <line>
#     <line>
#     ...
#     [conditional: <free text condition applying to all lines above>]
#   ]]
#
# Each <line> is one of:
#
#   move_to: <unit> -> <prov> by <phase>
#   not_move_to: <prov> by <phase>
#   hold_at: <unit> by <phase>
#   support: <unit> S <unit> [-> <prov>] by <phase>
#   non_aggression: with <power> [through <year>]
#   demilitarize: <prov> with <power> through <phase>
#   alliance_for: with <power> [vs <power>] through <year>
#   build: <kind><prov> in W<year>           # kind ∈ {A, F}
#   disband: <unit> in W<year>
#
# WHERE:
#   <unit>   ::= "A " <prov> | "F " <prov>
#   <prov>   ::= 3-letter province code (validated against engine's PROVINCES)
#   <power>  ::= full power name (validated)
#   <phase>  ::= <year>-<season>-<phase>      e.g. "1902-FALL-MOVES"
#                | <season><year>             e.g. "F1902"  (parser canonicalizes)
#
# EXAMPLE:
#
#   Marshal Veil to FRANCE (private):
#
#   "Sustained order serves us both. I propose we synchronize through autumn
#    and revisit terms in winter. Vienna will not march on Munich.
#
#    [[commit
#      not_move_to: MUN by 1902-FALL-MOVES
#      non_aggression: with FRANCE through 1903
#    ]]"
#
# PARSE FAILURE HANDLING:
#   - A malformed line produces a CommitmentNode with status=UNPARSEABLE and
#     the raw line preserved in raw_commitspeak_line for debugging. It does
#     NOT poison the rest of the block.
#   - A commitspeak block whose every line is unparseable is logged and the
#     speaker's prompt next turn includes a brief reminder of the grammar.
#     This is the small-model-feedback loop: malformed commitspeak teaches
#     the model to do better next time.

@dataclass
class CommitspeakLine:
    """One parsed line from a [[commit ...]] block.

    Successful parse → fields populated and a CommitmentNode is created.
    Failed parse → parse_errors populated; node created with UNPARSEABLE.
    """
    type: Optional[CommitmentType]
    raw: str
    subject_unit: Optional[str] = None
    subject_province: Optional[ProvinceCode] = None
    target_province: Optional[ProvinceCode] = None
    counterparty: Optional[PowerName] = None
    deadline_phase: Optional[PhaseKey] = None
    parse_errors: list[str] = field(default_factory=list)

    @property
    def parsed_ok(self) -> bool:
        return not self.parse_errors and self.type is not None


@dataclass
class CommitspeakBlock:
    """A parsed [[commit ...]] block. One per message at most."""
    raw_block: str
    lines: list[CommitspeakLine]
    conditional: Optional[str] = None           # the optional `conditional:` tail

    @property
    def well_formed_count(self) -> int:
        return sum(1 for l in self.lines if l.parsed_ok)


# =============================================================================
# LAYER 2 — Predictions (forward-looking falsifiable claims I make about others)
# =============================================================================
# Predictions feed the lifecycle. They're how the system gets graded on whether
# its model of others is accurate. A belief that spawns predictions which all
# refute is a belief in trouble; a belief whose predictions consistently
# confirm earns evidence weight.
#
# REQUIRED: every orders call must emit at least one prediction, and at least
# one of those predictions must have a near-term window (the immediately
# following resolved phase). This is the equivalent of magic_go's
# "every move generates a plan node" — it guarantees the lifecycle gets fresh
# grading signal every turn rather than starving when the LLM happens not to
# feel introspective.
#
# Longer-window predictions (multi-phase) are also welcome. They do NOT
# substitute for the near-term requirement. Both kinds register as nodes;
# the lifecycle treats them differently only in how patient the grader is
# about waiting for resolution.

class PredictionStatus(Enum):
    OPEN          = "open"
    CONFIRMED     = "confirmed"
    REFUTED       = "refuted"
    PARTIAL       = "partial"           # some sub-claims confirmed, others not
    SUPERSEDED    = "superseded"        # belief retired before window closed


class PredictionWindowKind(Enum):
    """Two kinds of windows. The lifecycle requires at least one NEAR_TERM
    per orders call; LONG_HORIZON predictions are bonus credit."""
    NEAR_TERM     = "near_term"        # resolves at the very next phase
    LONG_HORIZON  = "long_horizon"     # resolves multiple phases out


@dataclass
class PredictionNode:
    id: str
    about_power: PowerName
    formed_at_phase: PhaseKey

    # The prediction itself, structured for grading
    predicted_event_type: Literal["move_to", "attack", "support", "alliance",
                                  "non_action", "build_at", "elimination_of"]
    predicted_target: Optional[ProvinceCode]
    predicted_subject_power: Optional[PowerName]    # for "alliance" or "attack"
    prediction_window: PhaseKey                     # by-when
    window_kind: PredictionWindowKind

    confidence: float                                # 0..1, set at creation

    # Provenance — what beliefs/observations spawned this prediction
    source_belief_ids: list[str] = field(default_factory=list)
    source_message_ids: list[str] = field(default_factory=list)
    source_observation_ids: list[str] = field(default_factory=list)

    # If this prediction was generated as part of a strategic intent's
    # dependency chain — i.e., "this intent assumes Russia attacks Turkey by F1902."
    parent_intent_id: Optional[str] = None

    status: PredictionStatus = PredictionStatus.OPEN
    resolved_at_phase: Optional[PhaseKey] = None
    grading_evidence: list[str] = field(default_factory=list)

    # Free-text rationale (for inspect / human readability — never used in grading)
    rationale: str = ""


@dataclass
class TurnPredictionRequirement:
    """Bookkeeping for the per-turn prediction requirement.

    Created when an orders call begins. Used by the orders parser to
    confirm the LLM emitted at least one near-term prediction. If it
    didn't, the orders response is rejected and re-prompted with a
    pointed reminder.
    """
    phase: PhaseKey
    near_term_satisfied: bool = False
    total_predictions_emitted: int = 0
    rejected_reasons: list[str] = field(default_factory=list)


# =============================================================================
# LAYER 3 — Beliefs (theory of mind, properly grounded)
# =============================================================================
# This is the core layer. Every belief is a structured, falsifiable,
# evidence-attached claim about another power. Beliefs have head/body
# (your son's primitive, applied here): head is what the foveated prompt
# sees, body is the audit trail that inspect can pull.

class BeliefType(Enum):
    """Different belief types have different grading regimes and persistence."""

    DISPOSITION = "disposition"
    # Long-running character claims. Grades slowly against many events.
    # Persists across games. ("Marshal Veil tends to honor signed alliances.")

    TACTICAL_PATTERN = "tactical_pattern"
    # Recurring observed move pattern. Game-specific.
    # ("Russia opens with armies to GAL/UKR when paired with Austria.")
    # RESETS at start of new game.

    RELATIONSHIP = "relationship"
    # Pairwise dynamic. Game-specific.
    # ("Russia and Turkey are coordinating against Austria this game.")
    # RESETS at start of new game.

    RISK_ASSESSMENT = "risk_assessment"
    # Forward-looking threat. Short-lived.
    # ("Russia will move against me by 1903.")
    # Grades against specific events. RESETS at start of new game.

    CREDIBILITY = "credibility"
    # Persistent ledger of how this player honors commitments.
    # PERSISTS across games. Updated by commitment grading directly,
    # less by LLM proposal.


class BeliefStatus(Enum):
    PROTO     = "proto"        # newly proposed by the LLM, on probation
    ACTIVE    = "active"       # earned promotion
    RETIRED   = "retired"      # outcome record turned against it
    REVISED   = "revised"      # successor belief took its place


@dataclass
class BeliefNode:
    """A structured claim about another power.

    Head/body split (per AS's son's design):
      - `head` is what the foveated prompt sees (1-2 sentences).
      - `body` is the audit trail; only shown via inspect().

    The lifecycle's promote/retire/revise machinery operates on this node.
    """
    id: str
    about_power: PowerName
    belief_type: BeliefType

    # Display surfaces
    head: str                                       # gist; ≤ 2 sentences
    body: str                                       # full evidence narrative

    # Provenance + evidence
    formed_at_phase: PhaseKey
    formed_in_game: int                             # which game number created this
    last_updated_phase: PhaseKey

    evidence_for: list[str] = field(default_factory=list)
        # ids: MoveEvents, MessageEvents, CommitmentNodes (with kept status),
        #      PredictionNodes (with confirmed status)
    evidence_against: list[str] = field(default_factory=list)
        # same kinds, but contradicting

    # Lifecycle stats — Go-style
    hp: float = 1.0                                 # decays over time, recharged by use
    critic_score: float = 0.5                      # quality rating, 0..1
    success: float = 0.0                            # accumulated reward signal
    times_foveated: int = 0                         # hits — how often surfaced
    times_inspected: int = 0                        # body pulls — diagnostic

    status: BeliefStatus = BeliefStatus.PROTO

    # If retired, why
    retire_reason: Optional[Literal[
        "predictive_failure",      # predictions consistently refuted
        "belief_too_broad",        # head fires on every interaction (immune response)
        "superseded_by_revision",  # narrower successor took over
        "stale_idle",              # never foveated, decayed below hp threshold
        "game_ended_resettable",   # game-specific belief, not carried forward
        "target_eliminated",       # power this belief was about is no longer in the game
    ]] = None
    superseded_by: Optional[str] = None             # belief id of successor

    # Cross-game persistence
    persists_across_games: bool = False             # True for DISPOSITION, CREDIBILITY


@dataclass
class BeliefRevisionProposal:
    """An LLM-generated proposal to replace an active belief whose recent
    predictions have failed. Goes on probation — if its own predictions
    confirm, it supersedes the parent."""
    id: str
    parent_belief_id: str
    proposed_head: str
    proposed_body: str
    proposed_belief_type: BeliefType
    reason: str                                     # why revision was triggered
    triggering_prediction_ids: list[str]            # which failed predictions caused this

    formed_at_phase: PhaseKey
    status: Literal["probation", "promoted", "rejected"] = "probation"


# =============================================================================
# LAYER 4 — Strategy & planning (my plan, separate from theory of mind)
# =============================================================================
# This is what I am trying to do, distinct from what I think they are doing.
# Modeled on magic_go's strategy lifecycle:
#
#     proto_strategy → (earned via supporting plans + outcome wins) → active strategy
#     active strategy → (precondition fires too broadly | predictive failure) → retired
#     active strategy → (LLM proposes narrower successor) → revised
#
# Diplomacy translation:
#   - "supporting plans" become per-phase plan_nodes that the LLM emits at
#     orders time, naming which strategic_intent (if any) the move advances.
#   - "outcome wins" become predictions confirmed and SC gains realized.
#   - "precondition fires too broadly" becomes "this intent's preconditions
#     were satisfied for the last 4 phases but it never produced predicted
#     SC change" — the diplomacy-specific over-broad immune response.
#   - intent_commitment carries the same name as magic_go's strategy_commitment:
#     once an intent goes active, the agent commits to it for a configured
#     window of phases, and the commitment is reviewed at end of window.

class StrategicIntentStatus(Enum):
    PROTO     = "proto"        # newly proposed, on probation
    ACTIVE    = "active"       # earned promotion
    RETIRED   = "retired"      # outcome record turned against it
    REVISED   = "revised"      # successor took its place
    SUCCEEDED = "succeeded"    # horizon reached; predictions resolved favorably
    FAILED    = "failed"       # horizon reached; predictions did not resolve favorably


@dataclass
class StrategicIntentNode:
    """A high-level plan the agent is pursuing.

    Has the same lifecycle shape as magic_go's strategy nodes. New intents
    enter as PROTO; they earn ACTIVE status by accumulating supporting plans
    and confirming predictions; they can RETIRE if their predictions fail or
    if the immune response (intent fires too broadly, never delivers) kicks
    in; they can be REVISED by the LLM into a narrower successor.

    Head/body split as with beliefs:
      - `head` is what the foveated prompt sees.
      - `body` is the full plan; only via inspect().
    """
    id: str
    head: str                                       # "Solo run via Mediterranean by 1905"
    body: str                                       # full plan text
    formed_at_phase: PhaseKey

    target_powers: list[PowerName]                  # who this involves (allies + targets)
    target_provinces: list[ProvinceCode]            # what land it claims
    horizon: PhaseKey                               # phase by which to evaluate success/fail

    # Constraints derived from identity (personality / ethics nodes)
    requires_permits: list[str] = field(default_factory=list)
        # e.g. ["preemption_with_evidence"] — IDs of permit nodes
    violates_forbids: list[str] = field(default_factory=list)
        # IDs of forbid nodes; non-empty means LLM was asked to confirm or revise
    aligned_doctrines: list[str] = field(default_factory=list)
        # IDs of doctrine nodes the intent draws on

    # Predictions this intent depends on (the "this intent assumes ..." chain)
    depends_on_prediction_ids: list[str] = field(default_factory=list)

    # Plans that have advanced this intent across phases
    supporting_plan_ids: list[str] = field(default_factory=list)

    # Lifecycle stats (Go-style)
    hp: float = 1.0
    critic_score: float = 0.5
    success: float = 0.0                            # accumulated reward
    times_committed: int = 0                         # how often it has been the active commitment
    predictions_confirmed: int = 0
    predictions_refuted: int = 0
    sc_delta_under_intent: int = 0                  # net SCs gained while this was active

    status: StrategicIntentStatus = StrategicIntentStatus.PROTO
    active_since_phase: Optional[PhaseKey] = None        # set when promoted to ACTIVE

    succeeded_evidence: list[str] = field(default_factory=list)
    failed_evidence: list[str] = field(default_factory=list)

    # If retired/revised, why
    retire_reason: Optional[Literal[
        "predictive_failure",       # confirmed/refuted ratio fell below threshold
        "intent_too_broad",         # active for many phases, never produced predicted gain
        "horizon_passed_failed",    # horizon reached without success criteria met
        "superseded_by_revision",
        "stale_idle",
    ]] = None
    superseded_by: Optional[str] = None


@dataclass
class PlanNode:
    """A per-phase tactical plan, attached to a strategic intent.

    This is what magic_go called a 'plan node'. Every orders call emits one
    plan node describing the tactical reasoning for THIS phase's orders, and
    naming which strategic intent (if any) this plan is advancing.
    Plan nodes are the supporting evidence that lifts a proto-intent toward
    active status, and the supporting evidence that drives the active intent
    toward success.

    Plan nodes are short-lived: they live in the graph for a few phases and
    then archive or fold their stats up into the intent they supported.
    """
    id: str
    formed_at_phase: PhaseKey

    head: str                                       # 1-line tactical summary
    body: str                                       # full reasoning
    parent_intent_id: Optional[str]                  # which intent this plan advanced (or None)

    # Orders this plan motivated
    motivated_order_ids: list[str] = field(default_factory=list)
                                                    # MoveEvent ids once orders are issued

    # Predictions this plan emitted (the per-turn near-term ones)
    emitted_prediction_ids: list[str] = field(default_factory=list)

    # Outcome — graded once next phase resolves
    plan_outcome: Optional[Literal["advanced", "neutral", "setback"]] = None
    sc_delta_this_phase: int = 0                    # contributes to parent intent's running tally

    hp: float = 0.95                                 # plan nodes start near-full and decay fast
    critic_score: float = 0.5
    status: Literal["pending", "reviewed", "archived"] = "pending"


@dataclass
class IntentCommitmentNode:
    """A commitment to a strategic intent, parallel to magic_go's
    strategy_commitment mechanism.

    When an intent reaches ACTIVE status, the agent commits to it for a
    configured window of phases (default: 3 phases for a near-term intent,
    longer for campaign intents). During the commitment window, the intent's
    head appears in the foveated prompt as a working hypothesis ('YOUR
    PLAN: ...') so the LLM has a stable through-line.

    At end of window, the commitment is reviewed:
      - did the intent's predictions confirm at high rate?
      - did the SC delta meet the intent's expected gain?
      - did any of its forbids get violated?
    Result: completed | abandoned | extended.
    """
    id: str
    intent_id: str
    started_at_phase: PhaseKey
    window_phases: int                               # how long the commitment lasts

    phases_under_commitment: list[PhaseKey] = field(default_factory=list)
    plans_followed: int = 0                          # plan_nodes whose parent_intent matched
    plans_diverged: int = 0                          # plan_nodes that named a different intent or none
    predictions_confirmed_during: int = 0
    predictions_refuted_during: int = 0
    sc_delta_during: int = 0

    end_reason: Optional[Literal[
        "window_reached_completed",  # window finished, intent status updated to SUCCEEDED/FAILED
        "abandoned_too_many_divergences",
        "abandoned_predictive_failure",
        "extended",                  # the lifecycle decided to keep going
        "superseded",                # an intent revision replaced this commitment
    ]] = None
    ended_at_phase: Optional[PhaseKey] = None
    status: Literal["active", "completed", "abandoned", "extended"] = "active"


@dataclass
class StrategicIntentRevisionProposal:
    """Like BeliefRevisionProposal but for strategy.

    When an active intent's predictions are failing or its commitment was
    abandoned for predictive failure, the LLM is invited to propose a
    narrower successor. The successor enters as PROTO and earns its
    own promotion through its own supporting plans and predictions.
    """
    id: str
    parent_intent_id: str
    proposed_head: str
    proposed_body: str
    reason: Literal["commitment_abandoned", "predictive_failure",
                    "horizon_passed_failed", "intent_too_broad"]
    triggering_evidence_ids: list[str]               # plan/prediction IDs

    formed_at_phase: PhaseKey
    status: Literal["probation", "promoted", "rejected"] = "probation"


# =============================================================================
# LAYER 5 — Identity (immutable, seeded, protected)
# =============================================================================
# Personality, soul, ethics — kept but reduced in role. They drive the cached
# self-brief at game start, and they get consulted at SPECIFIC moments
# (intent proposal time, commitment composition time) — not dumped into every
# prompt.

@dataclass
class IdentityConstraintNode:
    """Immutable seed from personality archetype. Never retired, never
    revised, hp doesn't decay. Used to validate strategic intents and to
    flag actions inconsistent with stated ethics."""
    id: str
    kind: Literal["trait", "value", "fear", "desire", "permit", "forbid",
                  "doctrine", "credo"]
    label: str                                       # "honor_signed_alliances"
    weight: float                                    # strength from personality seed
    note: str                                        # human-readable elaboration
    archetype: str                                   # "MARSHAL_VEIL"


@dataclass
class CharacterBrief:
    """The first-person voice block, generated once at game start.
    This is what shows up at the top of every LLM prompt — NOT the full
    constraint graph. Same as your existing self_brief."""
    id: str
    archetype: str
    text: str                                        # ~150 words, first person
    generated_at: float


# =============================================================================
# THE BUNDLE — what an agent owns
# =============================================================================

@dataclass
class AgentMind:
    """The entire structured mind for one agent. Replaces AgentKGBundle."""
    owner_power: PowerName
    archetype: str

    # Layer 0 — observations (shared across agents in principle, but each
    # agent stores its own view because some events are private).
    move_events: dict[str, MoveEvent] = field(default_factory=dict)
    message_events: dict[str, MessageEvent] = field(default_factory=dict)
    phase_states: dict[str, PhaseState] = field(default_factory=dict)
    adjustment_events: dict[str, AdjustmentEvent] = field(default_factory=dict)

    # Layer 1 — commitments
    incoming_commitments: dict[str, CommitmentNode] = field(default_factory=dict)
    self_commitments: dict[str, SelfCommitmentNode] = field(default_factory=dict)

    # Layer 2 — predictions
    predictions: dict[str, PredictionNode] = field(default_factory=dict)

    # Layer 3 — beliefs
    beliefs: dict[str, BeliefNode] = field(default_factory=dict)
    belief_revisions: dict[str, BeliefRevisionProposal] = field(default_factory=dict)

    # Layer 4 — strategy lifecycle (full magic_go-style machinery)
    strategic_intents: dict[str, StrategicIntentNode] = field(default_factory=dict)
    plan_nodes: dict[str, PlanNode] = field(default_factory=dict)
    intent_commitments: dict[str, IntentCommitmentNode] = field(default_factory=dict)
    intent_revisions: dict[str, StrategicIntentRevisionProposal] = field(default_factory=dict)

    # Layer 5 — identity (immutable)
    identity_constraints: dict[str, IdentityConstraintNode] = field(default_factory=dict)
    character_brief: Optional[CharacterBrief] = None

    # Layer 6 — PRIVATE THOUGHTS (the agent's inner life across phases).
    # These are written by the agent itself in a dedicated journal call
    # after each phase resolves. They are never sent to other powers but
    # ARE included in the agent's own next-phase prompt as "your recent
    # private thoughts." Without them the agent has no way to carry
    # impressionistic suspicion or working hypothesis across turns.
    private_journal: list[dict] = field(default_factory=list)
    # Each entry: {"phase": str, "timestamp": float, "text": str,
    #              "kind": "post-negotiation" | "post-orders" | "post-resolution"}
    suspicions: list[dict] = field(default_factory=list)
    # Each: {"about_power": str, "tag": str, "note": str,
    #        "first_seen_phase": str, "last_seen_phase": str, "weight": float}

    # Cross-game persistent slice
    games_played: int = 0


# =============================================================================
# RETRIEVAL & FOVEA — how the prompt sees the mind
# =============================================================================

@dataclass
class FoveaSlot:
    """One narrow item that earned attention this turn.

    The full prompt's view of the mind is a small list of these — one
    selected belief per addressee, the open commitments due soonest, the
    current strategic intent. Not the full graph.
    """
    role: Literal["belief_about", "open_commitment_from", "open_commitment_to",
                  "active_intent", "credibility_summary"]
    target_power: Optional[PowerName]
    head_text: str
    node_id: str
    inspectable: bool = True


@dataclass
class TurnFovea:
    """The complete narrow surface for one turn's prompt. Replaces
    'render entire graph into prompt'."""
    phase: PhaseKey
    addressees: list[PowerName]                     # who we're talking to / planning against
    slots: list[FoveaSlot]
    strategic_intent_head: Optional[str]
    character_brief_text: str

    def render(self) -> str:
        """Compact text rendering for the prompt. Each slot one line."""
        lines = [self.character_brief_text, ""]
        if self.strategic_intent_head:
            lines.append(f"YOUR PLAN: {self.strategic_intent_head}")
            lines.append("")
        for slot in self.slots:
            tag = slot.role.upper()
            tgt = f" [{slot.target_power}]" if slot.target_power else ""
            lines.append(f"  {tag}{tgt}: {slot.head_text}")
        return "\n".join(lines)


# =============================================================================
# LIFECYCLE — the per-phase dream
# =============================================================================
# Sketched as function signatures only. Each is deterministic except where
# noted. The LLM is invited only at specific points (proto-belief proposal,
# revision proposal); the graders are pure code.

def grade_open_commitments(
    mind: AgentMind,
    just_resolved_phase: PhaseKey,
) -> list[CommitmentNode]:
    """Walk every PENDING commitment whose deadline_phase has now resolved.
    Compare grading_evidence against move_events / adjustment_events.
    Mark each kept | broken | irrelevant.
    Returns the list of newly-graded commitments for downstream cascading."""
    ...


def grade_open_predictions(
    mind: AgentMind,
    just_resolved_phase: PhaseKey,
) -> list[PredictionNode]:
    """Same but for predictions. Mark confirmed | refuted | partial.
    Updates evidence on the source beliefs."""
    ...


def update_credibility_from_commitments(
    mind: AgentMind,
    newly_graded: list[CommitmentNode],
) -> None:
    """For each kept/broken commitment, update the CREDIBILITY belief about
    that speaker. This is one of the few places trust changes deterministically.
    No LLM in the loop."""
    ...


def lifecycle_promote_proto_beliefs(mind: AgentMind) -> list[BeliefNode]:
    """Beliefs that have spawned ≥N predictions with ≥M confirmations and
    a passing confirm/refute ratio get promoted PROTO → ACTIVE.
    Returns promoted beliefs."""
    ...


def lifecycle_retire_active_beliefs(mind: AgentMind) -> list[BeliefNode]:
    """Active beliefs failing predictive tests, or whose head fires on every
    interaction (the broad-belief immune response from the Go system),
    get retired with the appropriate retire_reason. Returns retired."""
    ...


def lifecycle_invite_revisions(
    mind: AgentMind,
    failing_beliefs: list[BeliefNode],
) -> list[BeliefRevisionProposal]:
    """For each active belief whose recent predictions failed, prompt the
    LLM (one focused call per belief) to propose a narrower successor.
    LLM proposes; the revision goes on probation, NOT into active rotation.
    Its own predictions then determine whether it earns promotion."""
    ...


# ----- Strategy lifecycle (parallels the belief lifecycle above) -----

def lifecycle_review_plans(
    mind: AgentMind,
    just_resolved_phase: PhaseKey,
) -> list[PlanNode]:
    """For every PlanNode whose phase has just resolved, grade its outcome:
    advanced | neutral | setback (from sc_delta + predictions confirmed).
    Roll the plan's stats up into its parent_intent. Mark plan reviewed."""
    ...


def lifecycle_promote_proto_intents(
    mind: AgentMind,
) -> list[StrategicIntentNode]:
    """Proto-intents earn ACTIVE status when they have:
      - at least N supporting plans (default 2)
      - at least M confirmed predictions (default 2)
      - non-negative sc_delta_under_intent
      - a confirm/refute ratio above threshold (default 0.6)
    Returns the intents promoted this pass."""
    ...


def lifecycle_retire_active_intents(
    mind: AgentMind,
) -> list[StrategicIntentNode]:
    """Active intents fail/retire under three conditions:

      1. Predictive failure: the intent's recent predictions are refuting at
         a high rate (>40% of last 5).
      2. Intent too broad: the intent has been ACTIVE for ≥4 phases but its
         sc_delta_under_intent is still ≤0. This is the diplomacy analog of
         magic_go's `precondition_too_broad_unused` — an intent that 'fires
         on every board' but never delivers gets pulled, regardless of
         apparent activity.
      3. Horizon passed without success criteria: the intent reached its
         declared horizon without meeting its target.

    Each retired intent is a candidate for revision."""
    ...


def lifecycle_invite_intent_revisions(
    mind: AgentMind,
    failing_intents: list[StrategicIntentNode],
) -> list[StrategicIntentRevisionProposal]:
    """For each retired/failing intent, the LLM is invited to propose a
    narrower successor. Same probation pattern as belief revisions: the
    successor enters as PROTO and earns its own promotion."""
    ...


def lifecycle_review_intent_commitments(
    mind: AgentMind,
    just_resolved_phase: PhaseKey,
) -> list[IntentCommitmentNode]:
    """Intent commitments are reviewed when their window closes OR when
    divergence/predictive-failure thresholds are breached mid-window:

      - window reached → end_reason=window_reached_completed; intent
        gets SUCCEEDED if predictions confirmed at high rate AND sc_delta
        meets target, else FAILED.
      - too many plans diverged from the committed intent → abandoned.
      - too many predictions refuted under commitment → abandoned with
        predictive_failure (triggers revision).
    """
    ...


def lifecycle_decay_idle(mind: AgentMind) -> int:
    """HP decay on un-foveated nodes. Below threshold → archive.
    DISPOSITION and CREDIBILITY beliefs decay slower or not at all
    (cross-game persistence). Plan nodes decay faster (they are
    short-lived by design)."""
    ...


def lifecycle_reset_game_specific_beliefs(mind: AgentMind) -> int:
    """At new-game boundary: retire all TACTICAL_PATTERN, RELATIONSHIP, and
    RISK_ASSESSMENT beliefs with reason=game_ended_resettable.
    Also retire all StrategicIntentNodes (intent is always game-specific).
    DISPOSITION and CREDIBILITY beliefs persist."""
    ...


# =============================================================================
# THE TURN LOOP — how this all comes together
# =============================================================================
# Sketched as a dataflow comment, not code. Annotated by what's deterministic
# vs LLM-generated.
#
# 1. Engine resolves phase. -> deterministic
#    Captures MoveEvents, AdjustmentEvents, PhaseState into Layer 0.
#
# 2. grade_open_commitments() runs. -> deterministic
#    grade_open_predictions() runs. -> deterministic
#    update_credibility_from_commitments() runs. -> deterministic
#    lifecycle_review_plans() runs. -> deterministic
#    lifecycle_review_intent_commitments() runs. -> deterministic
#
# 3. Belief lifecycle pass: -> deterministic except revision proposal
#    promote_proto_beliefs, retire_active_beliefs, invite_revisions (LLM here),
#    decay_idle.
#
# 4. Strategy lifecycle pass: -> deterministic except revision proposal
#    promote_proto_intents, retire_active_intents, invite_intent_revisions
#    (LLM here). Active intents whose commitment windows just closed are
#    SUCCEEDED or FAILED based on prediction confirmation rate + sc_delta.
#
# 5. New phase begins. Build TurnFovea for this agent. -> deterministic
#    Per-addressee slot selection: pick the most relevant active belief,
#    soonest open commitment in/out, the actively-committed strategic intent
#    (if any). Plan nodes from the previous phase are NOT shown — they're
#    bookkeeping for the lifecycle, not for the prompt.
#
# 6. Negotiate call. -> LLM
#    Prompt contains: character_brief, fovea.render(), recent_messages_digest,
#    board_tag, addressees, COMMITSPEAK GRAMMAR REMINDER. LLM emits messages
#    with optional commitspeak tails. Tails are parsed at message-send time;
#    only well-formed lines become CommitmentNodes / SelfCommitmentNodes.
#
# 7. Parse commitspeak from outgoing messages we sent THIS turn (register as
#    SelfCommitmentNodes). Parse commitspeak from incoming messages addressed
#    to us (register as CommitmentNodes). Malformed lines logged for debug.
#    No NL extraction — promises in prose are not tracked.  -> deterministic
#
# 8. Orders call. -> LLM
#    Prompt contains: character_brief, fovea.render(), the actively-
#    committed strategic intent's head (if any), legal moves, and a
#    COMMITSPEAK + PREDICTION REQUIREMENT REMINDER.
#    LLM is REQUIRED to emit:
#      - one order per unit
#      - one PlanNode (head + body, naming parent_intent_id if any)
#      - at least one prediction with window_kind=NEAR_TERM
#      - optional additional predictions with window_kind=LONG_HORIZON
#      - optional proposed proto_belief or proto_intent
#    If the LLM fails to emit a near-term prediction, the orders response is
#    rejected and the prompt is re-issued with a pointed reminder. After two
#    failed attempts, the system synthesizes a default near-term prediction
#    from the issued orders ("you ordered A WAR -> GAL, so I'll register
#    'we predict A WAR moves to GAL by next phase'") so the lifecycle still
#    gets signal.
#
# 9. Register new predictions, plan_node, proto_belief, proto_intent as nodes.
#    All validated structurally; malformed entries are logged but do not
#    enter the graph.  -> deterministic
#
# 10. Engine resolves orders → goto step 1.

if __name__ == "__main__":
    # Quick sanity check that the dataclasses construct cleanly.
    m = AgentMind(owner_power="FRANCE", archetype="MARSHAL_VEIL")
    print(f"AgentMind for {m.owner_power} ({m.archetype}) built clean.")
    print(f"  layers initialized: "
          f"events={len(m.move_events)+len(m.message_events)+len(m.phase_states)}, "
          f"commitments={len(m.incoming_commitments)}, "
          f"predictions={len(m.predictions)}, "
          f"beliefs={len(m.beliefs)}, "
          f"intents={len(m.strategic_intents)}, "
          f"plans={len(m.plan_nodes)}, "
          f"intent_commitments={len(m.intent_commitments)}, "
          f"identity={len(m.identity_constraints)}.")

    # ---- Worked example: a commitspeak-bearing message and its parse ----
    print()
    print("---- Example message body + commitspeak tail ----")
    example_message = """\
Sustained order serves us both. Vienna will not march on Munich, and I would
welcome a similar restraint from your side regarding the Tyrol. We can revisit
terms in winter once the spring's tempo is clear.

[[commit
  not_move_to: MUN by 1902-FALL-MOVES
  non_aggression: with FRANCE through 1903
  conditional: only if you support A MAR holds
]]"""
    print(example_message)

    print()
    print("---- The resulting nodes (sketched, not parsed) ----")

    cs1 = CommitspeakLine(
        type=CommitmentType.NOT_MOVE_TO,
        raw="not_move_to: MUN by 1902-FALL-MOVES",
        subject_province="MUN",
        deadline_phase="1902-FALL-MOVES",
    )
    cs2 = CommitspeakLine(
        type=CommitmentType.NON_AGGRESSION,
        raw="non_aggression: with FRANCE through 1903",
        counterparty="FRANCE",
        deadline_phase="1903-WINTER-ADJUSTMENTS",  # canonicalized "through 1903"
    )
    block = CommitspeakBlock(
        raw_block="(elided)",
        lines=[cs1, cs2],
        conditional="only if you support A MAR holds",
    )

    n1 = SelfCommitmentNode(
        id=new_id("cmt"),
        source_msg_id="msg:abcd1234",
        speaker="AUSTRIA",
        addressees=["FRANCE"],
        type=CommitmentType.NOT_MOVE_TO,
        subject_unit=None,
        subject_province="MUN",
        target_province=None,
        counterparty=None,
        deadline_phase="1902-FALL-MOVES",
        conditional_on=block.conditional,
        target_power="FRANCE",
        raw_commitspeak_line=cs1.raw,
    )
    n2 = SelfCommitmentNode(
        id=new_id("cmt"),
        source_msg_id="msg:abcd1234",
        speaker="AUSTRIA",
        addressees=["FRANCE"],
        type=CommitmentType.NON_AGGRESSION,
        subject_unit=None,
        subject_province=None,
        target_province=None,
        counterparty="FRANCE",
        deadline_phase="1903-WINTER-ADJUSTMENTS",
        conditional_on=block.conditional,
        target_power="FRANCE",
        raw_commitspeak_line=cs2.raw,
    )

    for c in (n1, n2):
        print(f"  {c.id}  {c.type.value:<16} subj={c.subject_province or c.counterparty or '-'}"
              f"  by={c.deadline_phase}  cond={c.conditional_on or '-'}")
